services:
  taska-backend:
    image: ghcr.io/leonelnm/taska-api:latest
    container_name: taska-app
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      VIRTUAL_PORT: 8080
    env_file:
      - .env
    volumes:
      - /var/apps/taska/logs:/app/logs
    networks:
      - nginx-proxy
      - database-net

networks:
  nginx-proxy:
    external: true

  database-net:
    external: true