services:
  postgres:
    image: postgres:latest
    container_name: taska-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: taskauser
      POSTGRES_PASSWORD: taskapass
      POSTGRES_DB: taskadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: