services:
  taska-backend:
    image: ghcr.io/leonelnm/taska-api:latest
    container_name: taska-app
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - .env
    ports:
      - "8085:8080"
