services:
  taska:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taska-app-dev
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./mvnw:/app/mvnw
      - ./.mvn:/app/.mvn
    command: ./mvnw spring-boot:run
