spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/taskadb}
    username: ${DB_USER:taskauser}
    password: ${DB_PASS:taskapass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    com.codigozerocuatro: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    root: info

app:
  cors:
    allowed-origins:
      - http://localhost:5173
  user:
    default-password: password
  jwt:
    secret: mySecretKeyThatShouldBeVeryLongAndSecure123456789
    expiration: 60000  # 1 minuto en millisegundos
    refresh-expiration: 86400000 # 24 horas en millisegundos
