spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

logging:
  file.name: /app/logs/taska.log
  logback.rollingpolicy:
      max-file-size: 10MB
      max-history: 5
  level:
    root: warn

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}  # -> [http://origen1,http://origen2] un array separado por comas
  user:
    default-password: ${USER_DEFAULT_PASSWORD}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION}
