spring:
  application.name: taska

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    open-in-view: true

logging:
  level:
    root: info
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: error