-- SET TODAS LAS FECHA NULAS A LA FECHA ACTUAL
UPDATE public.tarea SET fecha = CURRENT_DATE WHERE fecha IS NULL;

-- ACTUALIZAR LA TABLA TAREA PARA HACER QUE LA COLUMNA FECHA NO PERMITA VALORES NULOS
ALTER TABLE public.tarea ALTER COLUMN fecha SET NOT NULL;