-- Tabla puesto
CREATE TABLE public.puesto
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    puesto VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT puesto_puesto_check CHECK (puesto IN ('ENCARGADO', 'COCINERO', 'CAMARERO', 'PINCHE'))
);

-- Tabla turno
CREATE TABLE public.turno
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turno VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT turno_turno_check CHECK (turno IN ('MANANA', 'MEDIO', 'TARDE'))
);

-- Tabla usuario
CREATE TABLE public.usuario
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(20)  NOT NULL UNIQUE,
    password            VARCHAR(255) NOT NULL,
    activo              BOOLEAN,
    nombre              VARCHAR(100),
    puesto              varchar(255) NOT NULL,
    rol                 varchar(255) NOT NULL,
    fecha_creacion      TIMESTAMP(6),
    fecha_actualizacion TIMESTAMP(6)
    CONSTRAINT usuario_puesto_check CHECK (puesto IN ('ENCARGADO', 'COCINERO', 'CAMARERO', 'PINCHE')),
    CONSTRAINT usuario_rol_check CHECK (rol IN ('ADMIN', 'USER'))
);

-- Tabla tarea
CREATE TABLE public.tarea
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    completada       BOOLEAN       NOT NULL DEFAULT false,
    descripcion      VARCHAR(3000) NOT NULL,
    dia_mes          INTEGER,
    dia_semana       VARCHAR(255),
    fecha            DATE,
    fecha_completada TIMESTAMP(6) WITH TIME ZONE,
    tipo_recurrencia VARCHAR(255) NOT NULL ,
    puesto_id        BIGINT,
    turno_id         BIGINT,
    CONSTRAINT tarea_dia_semana_check CHECK (dia_semana IN
                                             ('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO',
                                              'DOMINGO')),
    CONSTRAINT tarea_tipo_recurrencia_check CHECK (tipo_recurrencia IN
                                                   ('DIARIA', 'SEMANAL', 'QUINCENAL', 'MENSUAL', 'UNA_VEZ')),
    CONSTRAINT fk_tarea_puesto FOREIGN KEY (puesto_id) REFERENCES public.puesto (id),
    CONSTRAINT fk_tarea_turno FOREIGN KEY (turno_id) REFERENCES public.turno (id)
);
